In [1]:
import numpy as np

In [56]:
w = np.random.rand(82, 5)

In [5]:
x= np.random.rand(82,1101)

In [57]:
w_1 = w[1, :]

In [58]:
w_1.shape

(5,)

In [9]:
w[1].shape

(82,)

In [10]:
w.shape

(5, 82)

In [11]:
np.random.rand(5,82)

array([0.6413615 , 0.64528556, 0.97767708, 0.11044668, 0.6263588 ])

In [12]:
w_1 = w[:,1]

In [13]:
w_1

array([0.6413615 , 0.64528556, 0.97767708, 0.11044668, 0.6263588 ])

In [14]:
x_1 = x[1]

In [15]:
x_1.shape

(1101,)

In [22]:
np.dot(w_1.T, x_1)

ValueError: shapes (5,) and (1101,) not aligned: 5 (dim 0) != 1101 (dim 0)

In [26]:
x_1.shape

(1101,)

In [28]:
w_1.ravel().shape

(5,)

In [30]:
w_1.T*x_1

ValueError: operands could not be broadcast together with shapes (5,) (1101,) 

In [59]:
w_xx = w_1[:, np.newaxis]

In [60]:
w_xx.shape

(5, 1)

In [35]:
x_xx = x_1[:, np.newaxis]

In [37]:
x_xx.shape

(1101, 1)

In [61]:
y = np.dot(w_xx, x_xx.T)

In [62]:
y.shape

(5, 1101)

In [44]:
np.dot(w_xx.T, x_xx)

ValueError: shapes (1,5) and (1101,1) not aligned: 5 (dim 1) != 1101 (dim 0)

In [46]:
x_xx.T.shape

(1, 1101)

In [48]:
w_xx.shape

(5, 1)

In [49]:
w_xx.T.shape

(1, 5)

In [51]:
x_xx.shape

(1101, 1)

In [53]:
w_xx.shape

(5, 1)

In [54]:
np.dot(w_xx, x_xx)

ValueError: shapes (5,1) and (1101,1) not aligned: 1 (dim 1) != 1101 (dim 0)

In [55]:
x_xx.T.shape

(1, 1101)

In [63]:
import random

In [64]:
random.seed(0)

In [65]:
data = [[random.randint(1, 20) for _ in range(size)] for size in range(1, 5)]

In [67]:
for sample in data:
     print(sample)

[13]
[14, 2]
[9, 17, 16]
[13, 10, 16, 12]


In [69]:
data

[[13], [14, 2], [9, 17, 16], [13, 10, 16, 12]]

In [70]:
from scipy import stats

In [71]:
f_val, p_val = stats.f_oneway(*data)

In [72]:
p_val

0.5717214684807594

In [73]:
f_val

0.7277669902912621

In [74]:
w1

NameError: name 'w1' is not defined

In [76]:
w_1

array([0.53873696, 0.3652427 , 0.50877565, 0.37453089, 0.72196028])

In [79]:
w2_list = np.vstack((w_1, w_1))

In [80]:
w2_list

array([[0.53873696, 0.3652427 , 0.50877565, 0.37453089, 0.72196028],
       [0.53873696, 0.3652427 , 0.50877565, 0.37453089, 0.72196028]])